version: '3.8'
services:
  mongo:
    image: mongo:${MONGO_VERSION}
    restart: always
    container_name: auth-management-mongodb
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

  redis:
    image: redis:${REDIS_VERSION}
    container_name: auth-management-redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
